server:
#  port: ${PORT:8761}
  port: ${vcap.application.port:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

logging:
    file: eureka-server.log